name: BBE Website Generation

on: workflow_dispatch

jobs:
  bbe-generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2    
      
      - name: Clone ballerina-distribution Repository
        run: git clone https://github.com/ballerina-platform/ballerina-distribution.git

      - name: Copy Examples Directory into json-gen
        run: |
          cd bbe-generator/json-gen
          cp -r ../../ballerina-distribution/examples . 

      - name: Create and Grant Permissions for the Output Folder
        run: whoami      
          
      - name: Generate intermediate.json
        uses: ballerina-platform/ballerina-action@slbeta6
        with:
          args:
            run bbe-generator/json-gen/generate.bal

      - name: Create mdbook Folder
        run: mkdir ./bbe-generator/outputs/mdbook

      - name: Create mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook init --title "Ballerina By Examples" --ignore none ./bbe-generator/outputs/mdbook
          


      


