name: bbe-website-generation

on: [push]

jobs:
  bbe-generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
    
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args: 
            build
            
      - name: Ballerina Push
        uses: ballerina-platform/ballerina-action@master
        with:
          env: 
            BALLERINA_CENTRAL_ACCESS_TOKEN = ${{ secrets.BallerinaToken }}
          args: 
            push       
      
      - name: Check ballerina version
        run: bal -v


