name: bbe-website-generation

on: workflow_dispatch

jobs:
  bbe-generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Ballerina Action
        uses: ballerina-platform/ballerina-action@slbeta6
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm
      
      - name: Clone ballerina-distribution repo
        run: git clone https://github.com/ballerina-platform/ballerina-distribution.git

      - name: Execute JSON generation script
        run: |
          cd bbe-generator/json-gen
          cp -r ../../ballerina-distribution/examples/ .
          
          bal run generate.bal
          


      


