name: bbe-website-generation

on: workflow_dispatch

jobs:
  bbe-generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2    
      
      - name: Clone ballerina-distribution Repository
        run: git clone https://github.com/ballerina-platform/ballerina-distribution.git

      - name: Copy Examples Directory into json-gen
        run: |
          cd bbe-generator/json-gen
          cp -r ../../ballerina-distribution/examples .
          ls
          
      - name: Generate intermediate.json
        uses: ballerina-platform/ballerina-action@slbeta6
        with:
          args:
            run generate.bal
          


      


