name: BBE Website Generation

on: [push, workflow_dispatch]

jobs:
  bbe-generation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2    
      
      - name: Clone ballerina-distribution Repository
        run: git clone https://github.com/ballerina-platform/ballerina-distribution.git

      - name: Copy Examples Directory into json-gen
        run: |
          cd bbe-generator/json-gen
          cp -r ../../ballerina-distribution/examples . 
          
      - name: Create outputs folder
        run: |
          chmod -R +rwx ./bbe-generator
          mkdir ./bbe-generator/outputs
          
      - name: Generate intermediate.json
        uses: ballerina-platform/ballerina-action@slbeta6
        with:
          args:
            run bbe-generator/json-gen/generate.bal

      - name: Create mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook init --title "Ballerina By Examples" --ignore none ./bbe-generator/outputs/mdbook

      - name: Generate mdbook Content
        uses: ballerina-platform/ballerina-action@slbeta6
        with:
          args:
            run bbe-generator/md-gen/generate.bal       

      - name: Build mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build ./bbe-generator/outputs/mdbook

      - name: Clone ballerina-dev-website
        run: git clone https://github.com/YasithD/ballerina-dev-website.git

      - name: Copy HTML Files from the Build
        run: |
          rm -rf ./ballerina-dev-website/book 
          cp -r ./bbe-generator/outputs/mdbook/book ./ballerina-dev-website  
      
      - name: Config Git
        run: |
          git remote rm origin
          git remote add origin "git@github.com/YasithD/ballerina-release.git"
          git config --global user.email "yasith.18@cse.mrt.ac.lk"
          git config --global user.name "YasithD"
      
      - name: Commit and Push Changes
        run: |
          cd ./ballerina-dev-website
          git add .
          git commit -m "mdbook content updated"
          git push
               


      


